Repository anushkadixit1708/Projects_CSE, pull requests merged in 2022-10, with the labels that each got.

#3 Maze Game - 8086
  Maze Game/Maze Game.asm
  Maze Game/Report.pdf
Labels: hacktoberfest-accepted

#4 Traffic Sign Classifier
  Traffic Sign Classification/README.md
  Traffic Sign Classification/Testing Images/sample 1.jpg
  Traffic Sign Classification/Testing Images/sample 2.jpg
  Traffic Sign Classification/Testing Images/sample 3.jpg
  Traffic Sign Classification/Testing Images/sample 4.jpg
  Traffic Sign Classification/Testing Images/sample 5.jpg
  Traffic Sign Classification/Testing Images/sample 6.png
  Traffic Sign Classification/Traffic_Sign_Classifier.ipynb
  Traffic Sign Classification/readme resources/graph.png
  Traffic Sign Classification/readme resources/prediction.png
Labels: hacktoberfest-accepted

#5 Simple program to remind you with healthy tips
  HealthApp/engine.py
Labels: hacktoberfest-accepted

#8 Backend for meme generator
  meme-generator-backend/controllers/auth.js
  meme-generator-backend/middleware/auth.js
  meme-generator-backend/models/meme.js
  meme-generator-backend/models/users.js
  meme-generator-backend/package-lock.json
  meme-generator-backend/package.json
  meme-generator-backend/requests.rest
  meme-generator-backend/routes/auth.js
  meme-generator-backend/server.js
Labels: hacktoberfest-accepted

#9 meme-generator-frontend
  meme-generator-frontend/README.md
  meme-generator-frontend/package-lock.json
  meme-generator-frontend/package.json
  meme-generator-frontend/public/favicon.ico
  meme-generator-frontend/public/index.html
  meme-generator-frontend/public/logo192.png
  meme-generator-frontend/public/logo512.png
  meme-generator-frontend/public/manifest.json
  meme-generator-frontend/public/robots.txt
  meme-generator-frontend/src/App.js
  meme-generator-frontend/src/api/getMemes.js
  meme-generator-frontend/src/component/memeContainer.js
  meme-generator-frontend/src/index.js
  meme-generator-frontend/src/styles/App.css
  meme-generator-frontend/src/styles/MemeContainer.css
  meme-generator-frontend/src/styles/index.css
Labels: hacktoberfest-accepted

#10 Whatsapp-scheduler
  whatsapp-scheduled-reminders-backend/Dockerfile
  whatsapp-scheduled-reminders-backend/bin/start.sh
  whatsapp-scheduled-reminders-backend/docker-compose.yml
  whatsapp-scheduled-reminders-backend/index.js
  whatsapp-scheduled-reminders-backend/package-lock.json
  whatsapp-scheduled-reminders-backend/package.json
  whatsapp-scheduled-reminders-backend/queues/queue.js
  whatsapp-scheduled-reminders-backend/redis.conf
  whatsapp-scheduled-reminders-backend/req.rest
  whatsapp-scheduled-reminders-backend/routes/requests.js
  whatsapp-scheduled-reminders-backend/sendmessage.js
Labels: hacktoberfest-accepted

#11 Stopwatch app added
  Stopwatch/.DS_Store
  Stopwatch/_config.yml
  Stopwatch/audio/beep_cut.mp3
  Stopwatch/audio/sound_trim.mp3
  Stopwatch/clock.png
  Stopwatch/fonts/digital-7.ttf
  Stopwatch/img/favicon.png
  Stopwatch/img/light-mode.png
  Stopwatch/img/night.png
  Stopwatch/index.html
  Stopwatch/jquery.js
  Stopwatch/script.js
  Stopwatch/style.css
Labels: hacktoberfest-accepted

#13 Added Project
  event management website/about-us.html
  event management website/contact-us.html
  event management website/css/bootstrap.min.css
  event management website/css/fancybox.min.css
  event management website/css/font-awesome.min.css
  event management website/css/responsive.css
  event management website/css/slick-theme.css
  event management website/css/slick.css
  event management website/css/style.css
  event management website/images/brand-management.svg
  event management website/images/cel-3.jpg
  event management website/images/design-print.svg
  event management website/images/digital-marketing.svg
  event management website/images/email-icon.svg
  event management website/images/email.svg
  event management website/images/event-exhibitions.svg
  event management website/images/favicon.svg
  event management website/images/home.svg
  event management website/images/image-1.jpg
  event management website/images/image-2.jpg
  event management website/images/image-3.jpg
  event management website/images/image-4.jpg
  event management website/images/image-5.jpg
  event management website/images/image-6.jpg
  event management website/images/image-7.jpg
  event management website/images/image-8.jpg
  event management website/images/location-icon.svg
  event management website/images/logo-icon.svg
  event management website/images/mobile-icon.svg
  event management website/images/mrs-featured.jpg
  event management website/images/one.jpg
  event management website/images/orange-marketing-solutions-logo.svg
  event management website/images/play-large.svg
  event management website/images/profile-img.png
  event management website/images/project-1.jpg
  event management website/images/project-3.jpg
  event management website/images/project-4.jpg
  event management website/images/project-5.jpg
  event management website/images/project-6.jpg
  event management website/images/project-7.jpg
  event management website/images/project-8.jpg
  event management website/images/video-bg.png
  event management website/images/video-production.svg
  event management website/images/virtual-event.svg
  event management website/index.html
  event management website/js/bootstrap.bundle.js
  event management website/js/fancybox.min.js
  event management website/js/jquery.min.js
  event management website/js/script.js
  event management website/js/slick-animation.min.js
  event management website/js/slick.min.js
  event management website/video/video1.mp4
  event management website/video/video2.mp4
  event management website/video/video3.mp4
Labels: hacktoberfest-accepted

#14 NFT Vault authentication
  NFT_Authentication_vault/LICENSE
  NFT_Authentication_vault/README.md
  NFT_Authentication_vault/client/README.md
  NFT_Authentication_vault/client/package-lock.json
  NFT_Authentication_vault/client/package.json
  NFT_Authentication_vault/client/public/favicon.ico
  NFT_Authentication_vault/client/public/index.html
  NFT_Authentication_vault/client/public/logo192.png
  NFT_Authentication_vault/client/public/logo512.png
  NFT_Authentication_vault/client/public/manifest.json
  NFT_Authentication_vault/client/public/robots.txt
  NFT_Authentication_vault/client/src/App.css
  NFT_Authentication_vault/client/src/App.js
  NFT_Authentication_vault/client/src/App.test.js
  NFT_Authentication_vault/client/src/Components/Dashboard.jsx
  NFT_Authentication_vault/client/src/Components/UnAuthorized.jsx
  NFT_Authentication_vault/client/src/contracts/Address.json
  NFT_Authentication_vault/client/src/contracts/Counters.json
  NFT_Authentication_vault/client/src/contracts/ERC165.json
  NFT_Authentication_vault/client/src/contracts/ERC721.json
  NFT_Authentication_vault/client/src/contracts/ERC721Enumerable.json
  NFT_Authentication_vault/client/src/contracts/ERC721Full.json
  NFT_Authentication_vault/client/src/contracts/ERC721Metadata.json
  NFT_Authentication_vault/client/src/contracts/IERC165.json
  NFT_Authentication_vault/client/src/contracts/IERC721.json
  NFT_Authentication_vault/client/src/contracts/IERC721Enumerable.json
  NFT_Authentication_vault/client/src/contracts/IERC721Metadata.json
  NFT_Authentication_vault/client/src/contracts/IERC721Receiver.json
  NFT_Authentication_vault/client/src/contracts/Migrations.json
  NFT_Authentication_vault/client/src/contracts/SafeMath.json
  NFT_Authentication_vault/client/src/contracts/SimpleStorage.json
  NFT_Authentication_vault/client/src/contracts/User.json
  NFT_Authentication_vault/client/src/getWeb3.js
  NFT_Authentication_vault/client/src/index.css
  NFT_Authentication_vault/client/src/index.js
  NFT_Authentication_vault/client/src/logo.svg
  NFT_Authentication_vault/client/src/serviceWorker.js
  NFT_Authentication_vault/client/yarn.lock
  NFT_Authentication_vault/contracts/ERC721Full.sol
  NFT_Authentication_vault/contracts/Migrations.sol
  NFT_Authentication_vault/contracts/SimpleStorage.sol
  NFT_Authentication_vault/contracts/User.sol
  NFT_Authentication_vault/migrations/1_initial_migration.js
  NFT_Authentication_vault/migrations/2_deploy_contracts.js
  NFT_Authentication_vault/package-lock.json
  NFT_Authentication_vault/package.json
  NFT_Authentication_vault/test/TestSimpleStorage.sol
  NFT_Authentication_vault/test/simplestorage.js
  NFT_Authentication_vault/truffle-config.js
Labels: hacktoberfest-accepted

#15 Create Password generator
  Password_generator
Labels: hacktoberfest-accepted

#21 Know the Alphabets
  Know-the-Alphabets/README.md
  Know-the-Alphabets/package-lock.json
  Know-the-Alphabets/package.json
  Know-the-Alphabets/public/favicon.png
  Know-the-Alphabets/public/index.html
  Know-the-Alphabets/public/manifest.json
  Know-the-Alphabets/src/App.js
  Know-the-Alphabets/src/components/DisplayImage.js
  Know-the-Alphabets/src/components/DisplayText.js
  Know-the-Alphabets/src/components/Key.js
  Know-the-Alphabets/src/components/KeyBoard.js
  Know-the-Alphabets/src/components/KeysLine.js
  Know-the-Alphabets/src/components/Screen.js
  Know-the-Alphabets/src/images/apple.png
  Know-the-Alphabets/src/images/banana.png
  Know-the-Alphabets/src/images/cat.png
  Know-the-Alphabets/src/images/dog.png
  Know-the-Alphabets/src/images/eggs.png
  Know-the-Alphabets/src/images/fish.png
  Know-the-Alphabets/src/images/grapes.png
  Know-the-Alphabets/src/images/hat.png
  Know-the-Alphabets/src/images/ice.png
  Know-the-Alphabets/src/images/juice.png
  Know-the-Alphabets/src/images/keyboard.png
  Know-the-Alphabets/src/images/lion.png
  Know-the-Alphabets/src/images/mango.png
  Know-the-Alphabets/src/images/nose.png
  Know-the-Alphabets/src/images/owl.png
  Know-the-Alphabets/src/images/pencil.png
  Know-the-Alphabets/src/images/queen.png
  Know-the-Alphabets/src/images/rabbit.png
  Know-the-Alphabets/src/images/sun.png
  Know-the-Alphabets/src/images/tree.png
  Know-the-Alphabets/src/images/umbrella.png
  Know-the-Alphabets/src/images/van.png
  Know-the-Alphabets/src/images/watch.png
  Know-the-Alphabets/src/images/xylophone.png
  Know-the-Alphabets/src/images/yarn.png
  Know-the-Alphabets/src/images/zebra.png
  Know-the-Alphabets/src/index.css
  Know-the-Alphabets/src/index.js
  Know-the-Alphabets/src/styles/App.css
  Know-the-Alphabets/src/styles/DisplayImage.css
  Know-the-Alphabets/src/styles/DisplayText.css
  Know-the-Alphabets/src/styles/Key.css
  Know-the-Alphabets/src/styles/KeyBoard.css
  Know-the-Alphabets/src/styles/KeyLine.css
  Know-the-Alphabets/src/styles/Screen.css
Labels: hacktoberfest-accepted

#23 Added Gym_website frontend project
  Gym_Website/Gym_Website.css
  Gym_Website/Gym_Website.html
  Gym_Website/bg.png.jpg
  Gym_Website/icon.png.png
Labels: documentation, hacktoberfest-accepted

#25 Contact keeper
  React_Contact_Keeper/.gitignore
  React_Contact_Keeper/.vscode/settings.json
  React_Contact_Keeper/client/package-lock.json
  React_Contact_Keeper/client/package.json
  React_Contact_Keeper/client/public/favicon.ico
  React_Contact_Keeper/client/public/index.html
  React_Contact_Keeper/client/public/logo192.png
  React_Contact_Keeper/client/public/logo512.png
  React_Contact_Keeper/client/public/manifest.json
  React_Contact_Keeper/client/public/robots.txt
  React_Contact_Keeper/client/src/App.css
  React_Contact_Keeper/client/src/App.js
  React_Contact_Keeper/client/src/components/About.js
  React_Contact_Keeper/client/src/components/ContactFilter.js
  React_Contact_Keeper/client/src/components/ContactForm.js
  React_Contact_Keeper/client/src/components/ContactItem.js
  React_Contact_Keeper/client/src/components/Contacts.js
  React_Contact_Keeper/client/src/components/Home.js
  React_Contact_Keeper/client/src/components/Navbar.js
  React_Contact_Keeper/client/src/context/contact/ContactState.js
  React_Contact_Keeper/client/src/context/contact/contactContext.js
  React_Contact_Keeper/client/src/context/contact/contactReducer.js
  React_Contact_Keeper/client/src/context/types.js
  React_Contact_Keeper/client/src/index.js
  React_Contact_Keeper/config/db.js
  React_Contact_Keeper/middleware/auth.js
  React_Contact_Keeper/models/Contact.js
  React_Contact_Keeper/models/User.js
  React_Contact_Keeper/notes.txt
  React_Contact_Keeper/package-lock.json
  React_Contact_Keeper/package.json
  React_Contact_Keeper/routes/auth.js
  React_Contact_Keeper/routes/contacts.js
  React_Contact_Keeper/routes/users.js
  React_Contact_Keeper/server.js
Labels: hacktoberfest-accepted

#26 Added "Vulnerable Application Demonstration and Prevention" Project
  Vulnerable Application Demonstration and Prevention/SQL/sql1.php
  Vulnerable Application Demonstration and Prevention/SQL/sql2.php
  Vulnerable Application Demonstration and Prevention/SQL/sql3.php
  Vulnerable Application Demonstration and Prevention/SQL/sql4.php
  Vulnerable Application Demonstration and Prevention/SQL/sql5.php
  Vulnerable Application Demonstration and Prevention/SQL/sql_prevention.php
  Vulnerable Application Demonstration and Prevention/SQL/sqlmainpage.html
  Vulnerable Application Demonstration and Prevention/database.php
  Vulnerable Application Demonstration and Prevention/homepage.html
Labels: documentation, hacktoberfest-accepted

#28 To_do_list
  toodolist=v1/app.js
  toodolist=v1/index.html
  toodolist=v1/package-lock.json
  toodolist=v1/package.json
  toodolist=v1/public/css/styles.css
  toodolist=v1/views/list.ejs
Labels: hacktoberfest-accepted

#29 Bowling game using java
  Bowling Game/Bowling.java
Labels: hacktoberfest-accepted

#30 Create README.md
  Bowling Game/README.md
Labels: hacktoberfest-accepted

#31 Added new Project Regarding No touch button
  NO touch/animed.jpg
  NO touch/index.html
  NO touch/script.js
  NO touch/styl.css
Labels: hacktoberfest-accepted

#33 Added Background Changer using Html & JavaScript
  Background Changer/index.html
Labels: hacktoberfest-accepted

#35 Created Simple Table Generator
  Table Generator/index.html
Labels: hacktoberfest-accepted

#38 Hacktoberfest2022
  project.txt
Labels: invalid

#43 Added Image Retrieval System Using Texture,Color and Edge
  Image Retrieval System Using Texture,Color and Edge/Images/output1.JPG
  Image Retrieval System Using Texture,Color and Edge/Images/output2.JPG
  Image Retrieval System Using Texture,Color and Edge/README.md
  Image Retrieval System Using Texture,Color and Edge/cannyedge.m
  Image Retrieval System Using Texture,Color and Edge/edgefeature.m
  Image Retrieval System Using Texture,Color and Edge/lbpfeature.m
  Image Retrieval System Using Texture,Color and Edge/natsort.m
  Image Retrieval System Using Texture,Color and Edge/natsortfiles.m
  Image Retrieval System Using Texture,Color and Edge/natsortfiles_doc.m
  Image Retrieval System Using Texture,Color and Edge/projectmain.m
  Image Retrieval System Using Texture,Color and Edge/readme.txt
  Image Retrieval System Using Texture,Color and Edge/resize.m
  Image Retrieval System Using Texture,Color and Edge/similarity.m
  Image Retrieval System Using Texture,Color and Edge/start.m
Labels: hacktoberfest-accepted

#46 Bill Splitter
  Bill Splitter/edit.css
  Bill Splitter/index.html
  Bill Splitter/work.js
Labels: hacktoberfest-accepted

#50 Quiz App
  Quiz/finalPage.css
  Quiz/finalPage.html
  Quiz/index.html
  Quiz/quiz.css
  Quiz/quiz.html
  Quiz/quiz.js
  Quiz/score.css
  Quiz/score.html
  Quiz/score.js
  Quiz/style.css
  Quiz/work.js
Labels: hacktoberfest-accepted

#49 Football Club Website
  Football Club Website/README.md
  Football Club Website/action.css
  Football Club Website/index.html
Labels: hacktoberfest-accepted

#48 Animated Calculator
  AnimatedCalculator/README.md
  AnimatedCalculator/eidt.css
  AnimatedCalculator/index.html
  AnimatedCalculator/vanilla-tilt.js
Labels: hacktoberfest-accepted
